
skillMetadata:
  sections:
    - name: Login << Name of another section
      fields:
        - type: label
          label: Google account details for Keep access
        - name: email
          type: text
          label: GMail Address
          value: ""
        - name: password
          type: password
          label: Password (or App Password with MFA setup)
          value: ""
