
skillMetadata:
  sections:
    - name: Login details
      fields:
        - type: label
          label: Google account details for Keep access
        - name: keep_username
          type: email
          label: GMail Address
          value: ""
        - name: keep_password
          type: password
          label: Password (or MFA App Password)
          value: ""
